---

molecule_tests:
  tags: [vagrant]
  only: [/^pr-.*$/]
  except: ['triggers']
  image: quay.io/kubespray/vagrant:$KUBESPRAY_VERSION
  services: []
  stage: deploy-part1
  before_script:
    - tests/scripts/rebase.sh
    - apt-get update && apt-get install -y python3-pip
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - python -m pip install -r tests/requirements.txt
  script:
    - ./tests/scripts/molecule_run.sh

.vagrant:
  extends: .testcases
  variables:
    CI_PLATFORM: "vagrant"
    SSH_USER: "kubespray"
    VAGRANT_DEFAULT_PROVIDER: "libvirt"
  tags: [vagrant]
  only: [/^pr-.*$/]
  except: ['triggers']
  image: quay.io/kubespray/vagrant:$KUBESPRAY_VERSION
  services: []
  script:
    - vagrant up
  after_script:
    - vagrant destroy --force

vagrant_ubuntu18-flannel:
  stage: deploy-part2
  extends: .vagrant
  when: on_success